name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env from example
        run: |
          cp .env.example .env
          sed -i 's/GLPI_DB_NAME=/GLPI_DB_NAME=glpi/' .env
          sed -i 's/GLPI_DB_USER=/GLPI_DB_USER=glpi/' .env
          sed -i 's/GLPI_DB_PASSWORD=/GLPI_DB_PASSWORD=ci_password/' .env

      - name: Build containers
        uses: hoverkraft-tech/compose-action@v2.6.0
        with:
          compose-file: compose.yaml
          up-flags: "--no-start"
